### ISSUE TITLE
Migration to csproj

### ISSUE THREAD

**Issue by peterblazejewicz** [dpaquette/TagHelperSamples#50]
Hi folks,

Do you plan one? If yes, thanks -  I'll help with migration.

**Comment by dpaquette** [comment]
I was planning on waiting for RTM to do the migration to csproj. If we do it now with the RC, it means the project doesn't work with VS 2015 and the LTS release of .NET Core. We could do it in a branch and wait to merge it once the csproj tooling is completed.

What are your thoughts? What are the advantages to doing it now?

**Comment by peterblazejewicz** [comment]
> What are your thoughts? What are the advantages to doing it now?

I'm not able to use pre RC4 on my machine. I've found it frustrating to correctly setup a machine to support multi-runtime version of `dotnet` environment even if I read:
http://www.hanselman.com/blog/WheresDNVMSafelyRunningMultipleVersionsOfTheNETCoreSDKAndToolingWithGlobaljson.aspx
http://www.natemcmaster.com/blog/2017/02/01/project-json-to-csproj-part2/

Can you folks just create RC4 branch from master so it could updated alongside master?

**Comment by dpaquette** [comment]
I have created a branch called csproj_goodness. I won't have time to do the update right now but if you wanted to take a crack at it, just submit a PR to that branch and I would be happy to merge that in.

**Comment by peterblazejewicz** [comment]
I've setup a repo with one-to-one copy and executed `dotnet migrate` to investigate a way of upgrade. The web project fails on single action only involving GenFu tag helper initialization:
```text
 Executing ViewResult, running view at path /Views/Samples/GenFuTagHelper.cshtml.
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: The type initializer for 'TagHelperSamples.GenFu.GenFuTagHelper' threw an exception.
System.TypeInitializationException: The type initializer for 'TagHelperSamples.GenFu.GenFuTagHelper' threw an exception. ---> System.IO.FileNotFoundException: Could not find file '/Users/piotrblazejewicz/git/tag-helpers-samples-rc4/TagHelperSamples/src/TagHelperSamples.Web/project.json'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.DotNet.ProjectModel.ProjectReader.GetProject(String projectPath, ProjectReaderSettings settings)
   at Microsoft.DotNet.ProjectModel.ProjectContext.<CreateContextForEachFramework>d__45.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at TagHelperSamples.GenFu.GenFuTagHelper..cctor() in /Users/piotrblazejewicz/git/tag-helpers-samples-rc4/TagHelperSamples/src/TagHelperSamples.GenFu/GenFuTagHelper.cs:line 30
   --- End of inner exception stack trace ---
```
https://github.com/peterblazejewicz/tag-helpers-samples-rc4

Does it look its failing only on this block for some reason:
https://github.com/dpaquette/TagHelperSamples/blob/master/TagHelperSamples/src/TagHelperSamples.GenFu/GenFuTagHelper.cs#L28-L39

**Comment by peterblazejewicz** [comment]
I have updated the same project on the windows OS with VS 2017 RC and this persists. As I understand there is no api right now supporting the same routine to read current project info under .csproj:
https://github.com/dotnet/cli/issues/5650

**Comment by kiwiant** [comment]
I thought I was going mad with my own custom TagHelper not working so downloaded the TagHelperSample which worked. I then updated all the Nuget packages to the latest versions and the tag helpers stopped working.

Obviously something is afoot but as yet I have been unable to determine exactly what.

Built-in tag helpers continue to work (eg, form) with VS2017 RTM but custom tag helpers aren't highlighted as such in the mark-up (turquoise as opposed to blue).

I'm keen to see the results of the migration to see what I'm missing :-)

**Comment by dpaquette** [comment]
This is done! Thanks @Rick-Anderson
